# Generated by Django 5.1.7 on 2025-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
