# Generated by Django 5.1.7 on 2025-03-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoyolaSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoyolaSystem.emaillevel')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoyolaSystem.emailtype')),
            ],
        ),
    ]
